#pragma once
#pragma once


// Default Based on my setting
#define WD12_NOZZLE_TO_PROBE_OFFSET { -48.8, -7.4, -1.51 }

// If BLtouch connect to ZMin connector

#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

#define WD12_Z_CLEARANCE_DEPLOY_PROBE 15
#define WD12_MULTIPLE_PROBING 2
#define WD12_EXTRA_PROBING    1
#define WD12_Z_CLEARANCE_BETWEEN_PROBES 7
#define WD12_Z_CLEARANCE_MULTI_PROBE 7
#define WD12_Z_AFTER_PROBING 15
#define WD12_PROBING_NOZZLE_TEMP 170
#define WD12_PROBING_BED_TEMP    80
#define WD12_GRID_MAX_POINTS_X 5
#define WD12_GRID_MAX_POINTS_Y 5

#ifdef WD12_BLTOUCH
#define ENDSTOPPULLUPS
#define BLTOUCH
#define AUTO_BED_LEVELING_BILINEAR
#define PROBE_OFFSET_WIZARD
#endif