name: "tagged-release"

on:
  push:
    branches:
      - workflow_debug

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2    
      - name: Upload ${{ matrix.assets_env }} Assets Compiled
        uses: actions/upload-artifact@v2
        with:
          name: README.md2
          path: README.md
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            README.md