# This is a basic workflow to help you get started with Actions
name: Build Firmware

on:
  push:
    branches:
      - workflow_debug
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install minimal deps (pip && pipenv)
        run:  python -m pip install --upgrade pip pipenv  
      - name: Print a Welcome Message
        run: echo Welcome Builder !
      - name: Execute the pipenv install
        run: pipenv install
      - name: Execute platformio build
        run: |
          cd AutoBuild-MarlinFirware
          pipenv run platformio pipenv shell run -e wanhao__d12__230
